# This is the configuration file for the API service
# Description of this part is present in the `main.go` file

log:
  level: debug
DB:
  Filename: /tmp/database.db
  CleanupOnExit: true

#  methodname: false
#  json: false
#  destination: stderr
#  file: /tmp/debug.log
#  combinedtostdout: true
Web:
  APIHost: 0.0.0.0:3010
  DebugHost: 0.0.0.0:4010
#  readtimeout: 5s
#  writetimeout: 5s
#  shutdowntimeout: 5s
#  behindproxy: false
